dojo.provide("unieapx.nls.application_ja_JP");

RIA_UNIEAPX_I18N={
	
		query:{
			// 请输入整数！
			integerPrompt :" 整数を入力してください。",
			// 查询
			queryLabel :" 検索",
			// 清空
			clearLabel :" クリア",
			//您没有在Binding的数据源中配置RowSetName值！
			queryMessage:"バインドしたデータソースにRowSetNameの値を設定していません。",
			//匹配
			stringMatch:"完全一致",
			//左匹配
			stringLeftMatch:"前方一致",
			//右匹配
			stringRigthMatch:"後方一致",
			//不匹配
			stringNotMatch:"一致しない",
			//左不匹配
			stringLeftNotMatch:"前方不一致",
			//右不匹配
			stringRightNotMatch:"後方不一致",
			//等于
			numberEquals:"イコール",
			//不等于
			numberNotEquals:"ノットイコール",
			//大于
			numberGreaterThan:"大なり",
			//小于
			numberLessThan:"小なり",
			//大于等于
			numberGreaterThanOrEquals:"より大きいまたは等しい",
			//小于等于
			numberLessThanOrEquals:"より小さいまたは等しい",
			//查询项
			queryItem:"検索項目",
			//操作
			operation:"操作",
			//值
			value:"値",
			//关闭
			closeLabel:"閉じる",
			//新增
			addLabel:"新規追加",
			//修改
			modifyLabel:"変更",
			//删除
			deleteLabel:"削除",
			//请选择查询条件!
			chooseQueryCondition:"検索条件を選択してください",
			//不能添加重复条件!
			notDuplicateConditon:"重複した検索条件を追加することができません。",
			//是
			isTrue:"はい",
			//否
			isFalse:"いいえ",
			
			//検索条件の履歴がありません。
			noHistoryCondition:"検索条件の履歴がありません。",
			//削除しますか。
			confirmDelete:"削除しますか。",
			//検索条件を追加してください。
			addSelectConditon:"検索条件を追加してください。",
			//入力ボックス
			input:"入力ボックス",
			//検索条件名：
			coditionName:"検索条件名：",
			//保存しました。
			saveSuccess:"保存しました。",
			//追加した条件は既に存在しています。検索項目の値を変更してください。
			cantAddRepeatConditionDoUpdate:"追加した条件は既に存在しています。検索項目の値を変更してください。",
			//1件を選択してください。
			selectOndeData:"1件を選択してください。",
			//保存
			save:"保存",
			//条件
			condition:"条件"
		},
		exception:{
			//信息提示
			title:"メッセージ",
			//堆栈信息
			stackLabel:"スタック情報",
			//確認ダイアログ
			confirmTitle:"確認ダイアログ"
		},
		trace:{
			//提示
			infoTitle:"メッセージ",
			//请选择要删除的记录！
			unselectedInfo:"削除するレコードを選択してください。",
			//确认提示
			confirmTitle:"確認メッセージ",
			//确认要删除日志记录？
			confirmMessage:"ログを削除しますか。",
			//请选择一行记录进行查看！
			lookMessage:"レコードを1つ選択してください。",
			//堆栈信息
			stackTitle:"スタック情報",
			//信息列表
			infoList:"情報リスト",
			//概要信息
			summaryInfo:"概要情報",
			//操作人
			operator:"操作者",
			//发生时间
			occurTime:"発生時間"
		},
		menu:{
			//開いたメニューは最大数を超えています。
			theMenuNumOverMax:"開いたメニューは最大数を超えています。",
			//デスクトップ
			desktop:"デスクトップ",
			//現在メニューを閉じる
			closeCurrent:"現在メニューを閉じる",
			//他のメニューを閉じる
			closeOther:"他のメニューを閉じる",
			//すべてのメニューを閉じる
			closeAll:"すべてのメニューを閉じる",
			//InfoTipユーザ閲覧画面
			infoTipUsersBrowsePpage:"InfoTipユーザ閲覧画面",
			//クローズ
			close:"クローズ",
			//パスワード変更
			modifyPassword:"パスワード変更",
			//システムをロック
			lockSystem:"システムをロック",
			//ロック解除のパスワードを入力してください。
			inputUnlockPassword:"ロック解除のパスワードを入力してください。",
			//いいえ
			isFalse:"いいえ",
			//はい
			isTrue:"はい",
			//メニューを追加する
			addMenuItem:"メニューを追加する",
			//メニューを削除する
			deleteMenuItem:"メニューを削除する",
			//メニューを上へ移動する
			upMenuItem:"メニューを上へ移動する",
			//メニューを下へ移動する
			downMenuItem:"メニューを下へ移動する",
			//確認ダイアログ
			confirmTitle:"確認ダイアログ",
			//メニューの追加に失敗しました。
			addMenuItemFail:"メニューの追加に失敗しました。",
			//削除しますか。
			confirmDelete:"削除しますか。",
			//メニュー？
			isMenu:"メニュー？",
			//アプリケーションノードを削除することはできません。
			cantDeleteItem:"アプリケーションノードを削除することはできません。",
			//メニューの削除に失敗しました。
			delteMenuFail:"メニューの削除に失敗しました。",
			//入力したデータのフォーマットをチェックしてください。
			confirmData:"入力したデータのフォーマットをチェックしてください。",
			//メニュー名が重複しています。
			menuRepeat:"メニュー名が重複しています。",
			//メニューの保存に失敗しました。
			menuSaveFail:"メニューの保存に失敗しました。",
			//保存しました。
			saveSuccess:"保存しました。",
			//メニューをの移動に失敗しました。
			upMenuFail:"メニューをの移動に失敗しました。",
			//このメニューは上へ移動できません。
			cantUpMenu:"このメニューは上へ移動できません。",
			//アプリケーションノードを移動できません。
			cantMoveAppItem:"アプリケーションノードを移動できません。",
			//メニューをの移動に失敗しました。
			downMenuItemFail:"メニューをの移動に失敗しました。",
			//このメニューは下へ移動できません。
			cantDownMenu:"このメニューは下へ移動できません。",
			//データが変更されていません。
			dataNoChange:"データが変更されていません。",
			//メニュー項目のタイトルは必須入力です。
			menuTitleCantNull:"メニュー項目のタイトルは必須入力です。",
			//メニューノードを選択してください。
			selectMenuItem:"メニューノードを選択してください。"
		},
		form:{
			//メッセージ
			infoTilte:"メッセージ",
			//データの検索結果はありません。
			notFoundData:"データの検索結果はありません。"
		},
		layout:{
			//リクエスト開始
			beginRequest:"リクエスト開始"
		},
		indexApp:{
			//これは先頭のアプリです。
			isFirstApp:"これは先頭のアプリです。",
			//これは最後のアプリです。
			isLastApp:"これは最後のアプリです。"
		}
		
};
