insert into t_insurtype_acc_def (INSURTYPE_ACC_ID, INSURTYPE_ACC_TYPE, INSURTYPE_ACC_CODE, INSURTYPE_ACC_NAME, INSURTYPE_ACC_OWNER, RATE_TYPE, FIX_RATE, ACCRUAL_TYPE, ACCRUAL_METHOD, SETTLE_CYC, SETTLE_TYPE, IS_PROVISION, PROVISION_CYC, SETTLE_TIMEPOINT, INSERT_OPER, INSERT_TIME, UPDATE_OPER, UPDATE_TIME, INSERT_CONSIGNOR, UPDATE_CONSIGNOR)
values (85, '004', '000004', '红利账户', '1', '2', null, '3', '1', '12', '1', '0', '', '2', '', null, '', null, '', '');

insert into t_insurtype_acc_def (INSURTYPE_ACC_ID, INSURTYPE_ACC_TYPE, INSURTYPE_ACC_CODE, INSURTYPE_ACC_NAME, INSURTYPE_ACC_OWNER, RATE_TYPE, FIX_RATE, ACCRUAL_TYPE, ACCRUAL_METHOD, SETTLE_CYC, SETTLE_TYPE, IS_PROVISION, PROVISION_CYC, SETTLE_TIMEPOINT, INSERT_OPER, INSERT_TIME, UPDATE_OPER, UPDATE_TIME, INSERT_CONSIGNOR, UPDATE_CONSIGNOR)
values (86, '005', '000005', '生存金账户', '1', '2', null, '3', '1', '12', '1', '0', '', '2', '', null, '', null, '', '');

